import { useEffect,useMemo,useRef,useState } from 'react';
import type { Artboard,DesignElement,DesignShapeKind,DesignTemplate,DesignUnit,ImageDesignElement,ShapeDesignElement,TextDesignElement } from '@document-tool/contracts';
import {
  ARTBOARD_PRESETS,addArtboard,addAssetReference,addDesignElement,createBlankArtboard,createImageElement,createShapeElement,createTextElement,
  deleteArtboard,deleteDesignElements,duplicateArtboard,emptySelection,getSelectionBounds,mmToUnit,moveArtboard,moveElements,nextElementZIndex,
  normalizeDisplayValue,nudgeElements,renameArtboard,resizeArtboard,resizeElement,rotateElement,sanitizeSelection,selectAllSelectable,selectByMarquee,
  selectedElements,selectOnly,setArtboardBackground,setArtboardDisplayUnit,setElementPosition,toggleSelection,unitToMm,updateDesignElement,
  orderedLayers,renameElement,setElementVisibility,setElementLocked,moveLayer,duplicateDesignElements,groupElements,ungroupElements,
  expandElementIdsToGroups,groupForElement,setGroupLocked,setGroupVisibility,scaleElements,rotateElementsAsGroup,
  createDesignHistory,commitDesignHistory,undoDesignHistory,redoDesignHistory,resetDesignHistory,
  createDesignClipboardPayload,pasteDesignClipboard,createCorporateEmployeeIdTemplate
} from '@document-tool/design-engine';
import type { DesignClipboardPayload,DesignHistoryState,DesignRectMm,DesignSelectionState } from '@document-tool/design-engine';
import { LocalStorageDesignTemplateRepository } from '@document-tool/persistence';
import { ArrowDown,ArrowUp,ClipboardPaste,Copy,FilePlus2,ImagePlus,Maximize2,Minus,MonitorUp,Plus,Redo2,RotateCcw,Save,Square,Trash2,Type,Undo2 } from 'lucide-react';

const MM_TO_CSS_PX=96/25.4,MIN_ZOOM=25,MAX_ZOOM=200;
const SHAPES:DesignShapeKind[]=['RECTANGLE','ROUNDED_RECTANGLE','CIRCLE','ELLIPSE','LINE','TRIANGLE','ARROW','STAR','POLYGON','RIBBON','BADGE'];
const id=(p:string)=>`${p}-${globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(16).slice(2)}`}`;
function fresh():DesignTemplate{return{kind:'CARD_DESIGN',schemaVersion:1,id:id('card-template'),name:'Untitled Card Design',version:1,status:'DRAFT',artboards:[createBlankArtboard({id:id('artboard'),name:'Front',order:0,widthMm:90,heightMm:50})],sharedAssets:[]};}

export function CardDesigner(){
 const repo=useMemo(()=>new LocalStorageDesignTemplateRepository(window.localStorage),[]);
 const [template,setTemplate]=useState<DesignTemplate>(()=>fresh());
 const [activeId,setActiveId]=useState('');
 const [zoom,setZoom]=useState(100);
 const [status,setStatus]=useState('Ready');
 const [dirty,setDirty]=useState(false);
 const [space,setSpace]=useState(false);
 const [selection,setSelection]=useState<DesignSelectionState>(()=>emptySelection(''));
 const viewport=useRef<HTMLDivElement|null>(null);
 const pan=useRef<{x:number;y:number;left:number;top:number}|null>(null);
 const uploadRef=useRef<HTMLInputElement|null>(null);
 const templateRef=useRef(template);
 const historyRef=useRef<DesignHistoryState>(createDesignHistory(template));
 const historyTransactionRef=useRef<DesignTemplate|null>(null);
 const clipboardRef=useRef<DesignClipboardPayload|null>(null);
 const pasteCountRef=useRef(0);
 const [historyVersion,setHistoryVersion]=useState(0);
 const artboards=useMemo(()=>[...template.artboards].sort((a,b)=>a.order-b.order),[template.artboards]);
 const active=artboards.find(a=>a.id===activeId)??artboards[0];
 templateRef.current=template;
 const refreshHistory=()=>setHistoryVersion(v=>v+1);
 const resetHistory=(next:DesignTemplate)=>{historyRef.current=resetDesignHistory(next);historyTransactionRef.current=null;refreshHistory();};
 const recordHistory=(before:DesignTemplate,after:DesignTemplate)=>{if(before===after)return;const seeded={...historyRef.current,present:before};historyRef.current=commitDesignHistory(seeded,after);refreshHistory();};
 const mutate=(fn:(t:DesignTemplate)=>DesignTemplate,record=true)=>{setTemplate(current=>{const next=fn(current);if(next===current)return current;if(record&&!historyTransactionRef.current)recordHistory(current,next);templateRef.current=next;return next;});setDirty(true);setStatus('Unsaved changes');};
 const mutateTransient=(fn:(t:DesignTemplate)=>DesignTemplate)=>mutate(fn,false);
 const beginHistoryTransaction=()=>{if(!historyTransactionRef.current)historyTransactionRef.current=templateRef.current;};
 const endHistoryTransaction=()=>{const before=historyTransactionRef.current;historyTransactionRef.current=null;if(before&&before!==templateRef.current)recordHistory(before,templateRef.current);};
 const undo=()=>{const current=templateRef.current;const seeded={...historyRef.current,present:current};const next=undoDesignHistory(seeded);if(next===seeded)return;historyRef.current=next;templateRef.current=next.present;setTemplate(next.present);setDirty(true);setStatus('Undo');refreshHistory();};
 const redo=()=>{const current=templateRef.current;const seeded={...historyRef.current,present:current};const next=redoDesignHistory(seeded);if(next===seeded)return;historyRef.current=next;templateRef.current=next.present;setTemplate(next.present);setDirty(true);setStatus('Redo');refreshHistory();};
 const copySelected=()=>{if(!active||!selection.elementIds.length)return;const ids=expandElementIdsToGroups(active,selection.elementIds);const payload=createDesignClipboardPayload(templateRef.current,active.id,ids);if(!payload)return;clipboardRef.current=payload;pasteCountRef.current=0;setStatus(`${payload.elements.length} element${payload.elements.length===1?'':'s'} copied`);refreshHistory();};
 const pasteClipboard=()=>{if(!active||!clipboardRef.current)return;pasteCountRef.current+=1;let pastedIds:string[]=[];const offset={xMm:2*pasteCountRef.current,yMm:2*pasteCountRef.current};mutate(t=>{const result=pasteDesignClipboard(t,active.id,clipboardRef.current!,()=>id('paste'),offset);pastedIds=result.elementIds;return result.template;});setSelection({artboardId:active.id,elementIds:pastedIds,primaryElementId:pastedIds.length?pastedIds[pastedIds.length-1]:undefined});setStatus(`Pasted ${pastedIds.length} element${pastedIds.length===1?'':'s'}`);};

 useEffect(()=>{let cancelled=false;(async()=>{try{const activeTemplateId=await repo.getActiveId();const stored=activeTemplateId?await repo.getById(activeTemplateId):(await repo.list())[0]??null;if(cancelled)return;if(stored){setTemplate(stored);templateRef.current=stored;resetHistory(stored);const aid=[...stored.artboards].sort((a,b)=>a.order-b.order)[0]?.id??'';setActiveId(aid);setSelection(emptySelection(aid));setStatus('Draft restored');}else{const f=fresh();setTemplate(f);templateRef.current=f;resetHistory(f);setActiveId(f.artboards[0]!.id);setSelection(emptySelection(f.artboards[0]!.id));}}catch(e){if(!cancelled)setStatus(e instanceof Error?e.message:'Unable to restore card draft.');}})();return()=>{cancelled=true};},[repo]);
 useEffect(()=>{if(active)setSelection(s=>sanitizeSelection(s,active));},[active]);
 useEffect(()=>{const kd=(e:KeyboardEvent)=>{if(e.code==='Space'&&!isForm(e.target)){setSpace(true);e.preventDefault();return;}if(!active||isForm(e.target))return;const command=e.ctrlKey||e.metaKey;if(command&&e.key.toLowerCase()==='z'){e.preventDefault();if(e.shiftKey)redo();else undo();return;}if(command&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return;}if(command&&e.key.toLowerCase()==='c'){e.preventDefault();copySelected();return;}if(command&&e.key.toLowerCase()==='v'){e.preventDefault();pasteClipboard();return;}if(command&&e.key.toLowerCase()==='d'&&selection.elementIds.length){e.preventDefault();duplicateSelected();return;}if(command&&e.key.toLowerCase()==='a'){e.preventDefault();setSelection(selectAllSelectable(active));return;}if(e.key==='Escape'){setSelection(emptySelection(active.id));return;}if((e.key==='Delete'||e.key==='Backspace')&&selection.elementIds.length){e.preventDefault();mutate(t=>deleteDesignElements(t,active.id,selection.elementIds));setSelection(emptySelection(active.id));setStatus('Element deleted');return;}const dir=e.key==='ArrowLeft'?'LEFT':e.key==='ArrowRight'?'RIGHT':e.key==='ArrowUp'?'UP':e.key==='ArrowDown'?'DOWN':null;if(dir&&selection.elementIds.length){e.preventDefault();mutate(t=>nudgeElements(t,active.id,selection.elementIds,dir,e.shiftKey));setStatus('Unsaved changes');}},ku=(e:KeyboardEvent)=>{if(e.code==='Space')setSpace(false)};window.addEventListener('keydown',kd);window.addEventListener('keyup',ku);return()=>{window.removeEventListener('keydown',kd);window.removeEventListener('keyup',ku)};},[active,selection.elementIds,historyVersion]);
 const save=async()=>{try{await repo.save(template);await repo.setActiveId(template.id);setDirty(false);setStatus('Saved locally');}catch(e){setStatus(e instanceof Error?e.message:'Save failed');}};
 const newDesign=()=>{if(dirty&&!window.confirm('Discard unsaved Card Designer changes?'))return;const f=fresh();setTemplate(f);templateRef.current=f;resetHistory(f);setActiveId(f.artboards[0]!.id);setSelection(emptySelection(f.artboards[0]!.id));setZoom(100);setDirty(true);setStatus('New card design');};
 const loadCorporateIdTemplate=()=>{if(dirty&&!window.confirm('Replace current unsaved design with the default Corporate Employee ID Card template?'))return;const next=createCorporateEmployeeIdTemplate(id);setTemplate(next);templateRef.current=next;resetHistory(next);setActiveId(next.artboards[0]!.id);setSelection(emptySelection(next.artboards[0]!.id));setZoom(100);setDirty(true);setStatus('Corporate Employee ID Card template loaded');};
 const chooseArtboard=(aid:string)=>{setActiveId(aid);setSelection(emptySelection(aid));};
 const add=()=>{if(!active)return;const a=createBlankArtboard({id:id('artboard'),name:`Artboard ${template.artboards.length+1}`,order:template.artboards.length,widthMm:active.widthMm,heightMm:active.heightMm,displayUnit:active.displayUnit});mutate(t=>addArtboard(t,a));chooseArtboard(a.id);};
 const duplicate=()=>{if(!active)return;const nextId=id('artboard');mutate(t=>duplicateArtboard(t,active.id,nextId));chooseArtboard(nextId);};
 const remove=()=>{if(!active)return;if(template.artboards.length<=1){setStatus('A design must keep at least one artboard.');return;}if(!window.confirm(`Delete “${active.name}”?`))return;const i=artboards.findIndex(a=>a.id===active.id),next=artboards[i+1]??artboards[i-1];mutate(t=>deleteArtboard(t,active.id));chooseArtboard(next?.id??'');};
 const fit=()=>{const v=viewport.current;if(!v||!active)return;const z=Math.floor(Math.min(Math.max(100,v.clientWidth-96)/(active.widthMm*MM_TO_CSS_PX),Math.max(100,v.clientHeight-96)/(active.heightMm*MM_TO_CSS_PX))*100);setZoom(clamp(z,MIN_ZOOM,MAX_ZOOM));};
 const selectInserted=(elementId:string)=>{if(!active)return;setSelection(selectOnly(active.id,elementId));setStatus('Element added');};
 const insertText=()=>{if(!active)return;const eid=id('text');mutate(t=>addDesignElement(t,active.id,createTextElement({id:eid,name:'Text',xMm:Math.max(2,(active.widthMm-45)/2),yMm:Math.max(2,(active.heightMm-12)/2),zIndex:nextElementZIndex(t,active.id)})));selectInserted(eid);};
 const insertShape=(shape:DesignShapeKind='RECTANGLE')=>{if(!active)return;const eid=id('shape');mutate(t=>addDesignElement(t,active.id,createShapeElement(shape,{id:eid,xMm:Math.max(2,(active.widthMm-28)/2),yMm:Math.max(2,(active.heightMm-18)/2),zIndex:nextElementZIndex(t,active.id)})));selectInserted(eid);};
 const groupSelected=()=>{if(!active||selection.elementIds.length<2)return;const gid=id('group');mutate(t=>groupElements(t,active.id,selection.elementIds,gid,`Group ${active.groups.length+1}`));setSelection({...selection,elementIds:expandElementIdsToGroups({...active,groups:[...active.groups,{id:gid,name:`Group ${active.groups.length+1}`,elementIds:selection.elementIds}],elements:active.elements.map(e=>selection.elementIds.includes(e.id)?{...e,groupId:gid}:e)},selection.elementIds)});setStatus('Elements grouped');};
 const ungroupSelected=()=>{if(!active)return;const gids=[...new Set(selection.elementIds.map(eid=>groupForElement(active,eid)?.id).filter(Boolean) as string[])];if(!gids.length)return;mutate(t=>gids.reduce((acc,gid)=>ungroupElements(acc,active.id,gid),t));setStatus('Group removed');};
 const duplicateSelected=()=>{if(!active||!selection.elementIds.length)return;let newIds:string[]=[];mutate(t=>{const r=duplicateDesignElements(t,active.id,expandElementIdsToGroups(active,selection.elementIds),()=>id('element-copy'));newIds=r.elementIds;return r.template;});setSelection({artboardId:active.id,elementIds:newIds,primaryElementId:newIds.length > 0 ? newIds[newIds.length - 1] : undefined});setStatus('Selection duplicated');};
 const uploadImage=async(file:File)=>{if(!active)return;if(!file.type.startsWith('image/')){setStatus('Select a supported image file.');return;}try{const dataUrl=await readAsDataUrl(file);const dims=await readImageDimensions(dataUrl);const assetId=id('asset'),elementId=id('image');const ratio=dims.widthPx>0&&dims.heightPx>0?dims.widthPx/dims.heightPx:1.4;const width=Math.min(40,Math.max(15,active.widthMm*.45)),height=Math.min(active.heightMm*.6,width/ratio);mutate(t=>{let next=addAssetReference(t,{id:assetId,name:file.name,kind:'IMAGE',sourceType:'DATA_URL',source:dataUrl,mimeType:file.type,widthPx:dims.widthPx,heightPx:dims.heightPx});next=addDesignElement(next,active.id,createImageElement(assetId,{id:elementId,name:file.name,xMm:Math.max(2,(active.widthMm-width)/2),yMm:Math.max(2,(active.heightMm-height)/2),widthMm:width,heightMm:height,zIndex:nextElementZIndex(next,active.id)}));return next;});selectInserted(elementId);}catch(e){setStatus(e instanceof Error?e.message:'Image upload failed');}};
 if(!active)return <div className="card-designer-loading">Preparing Card Designer…</div>;
 const selected=selectedElements(active,selection),primary=selected.find(e=>e.id===selection.primaryElementId)??selected[0];
 return <div className="card-designer-page animated-fade-in">
  <header className="card-designer-commandbar"><div className="card-designer-title"><span className="designer-eyebrow">Visual Design Studio</span><input aria-label="Template name" value={template.name} onChange={e=>mutate(t=>({...t,name:e.target.value}))}/><span className="card-draft-badge">Draft</span></div><div className="card-designer-actions"><button title="Undo (Ctrl+Z)" onClick={undo} disabled={!historyRef.current.past.length}><Undo2 size={15}/>Undo</button><button title="Redo (Ctrl+Y)" onClick={redo} disabled={!historyRef.current.future.length}><Redo2 size={15}/>Redo</button><button title="Copy (Ctrl+C)" onClick={copySelected} disabled={!selection.elementIds.length}><Copy size={15}/>Copy</button><button title="Paste (Ctrl+V)" onClick={pasteClipboard} disabled={!clipboardRef.current}><ClipboardPaste size={15}/>Paste</button><button onClick={newDesign}><FilePlus2 size={15}/>New</button><button onClick={loadCorporateIdTemplate} title="Load editable CR80 Front + Back starter template">ID Card Template</button><button className="primary" onClick={save}><Save size={15}/>Save</button></div></header>
  <div className="card-designer-shell">
   <aside className="card-artboard-panel">
    <div className="card-elements-toolbox"><div className="card-toolbox-title"><strong>Starter Templates</strong><small>Editable defaults</small></div><button className="card-starter-template-button" onClick={loadCorporateIdTemplate}><strong>Corporate Employee ID Card</strong><span>CR80 · Front + Back · 85.60 × 53.98 mm</span></button></div><div className="card-elements-toolbox"><div className="card-toolbox-title"><strong>Elements</strong><small>Phase 6.0.4</small></div><div className="card-tool-grid"><button onClick={insertText}><Type size={17}/><span>Text</span></button><button onClick={()=>insertShape('RECTANGLE')}><Square size={17}/><span>Shape</span></button><button onClick={()=>uploadRef.current?.click()}><ImagePlus size={17}/><span>Image</span></button></div><select aria-label="Quick shape" defaultValue="" onChange={e=>{if(e.target.value){insertShape(e.target.value as DesignShapeKind);e.currentTarget.value='';}}}><option value="">More shapes…</option>{SHAPES.map(s=><option key={s} value={s}>{shapeLabel(s)}</option>)}</select><input ref={uploadRef} hidden type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{const f=e.target.files?.[0];if(f)void uploadImage(f);e.currentTarget.value='';}}/></div>
    <div className="card-panel-heading"><div><strong>Artboards</strong><small>{artboards.length} surface{artboards.length===1?'':'s'}</small></div><button title="Add artboard" onClick={add}><Plus size={16}/></button></div>
    <div className="artboard-list">{artboards.map((a,i)=><button key={a.id} className={`artboard-list-item ${a.id===active.id?'active':''}`} onClick={()=>chooseArtboard(a.id)}><span className="artboard-index">{i+1}</span><span><strong>{a.name}</strong><small>{sizeText(a)}</small></span></button>)}</div>
    <div className="artboard-panel-actions"><button onClick={duplicate}><Copy size={14}/>Duplicate</button><button onClick={()=>mutate(t=>moveArtboard(t,active.id,-1))} disabled={active.order===0}><ArrowUp size={14}/>Up</button><button onClick={()=>mutate(t=>moveArtboard(t,active.id,1))} disabled={active.order===artboards.length-1}><ArrowDown size={14}/>Down</button><button className="danger" onClick={remove}><Trash2 size={14}/>Delete</button></div>
    <LayerPanel artboard={active} selection={selection} setSelection={setSelection} mutate={mutate} duplicateSelected={duplicateSelected} groupSelected={groupSelected} ungroupSelected={ungroupSelected}/>
   </aside>
   <section className="card-canvas-column"><div className="card-canvas-toolbar"><div className="canvas-artboard-name"><MonitorUp size={15}/><strong>{active.name}</strong><span>{active.widthMm} × {active.heightMm} mm</span></div><div className="canvas-zoom-controls"><button onClick={()=>setZoom(z=>clamp(z-10,MIN_ZOOM,MAX_ZOOM))}><Minus size={15}/></button><span>{zoom}%</span><button onClick={()=>setZoom(z=>clamp(z+10,MIN_ZOOM,MAX_ZOOM))}><Plus size={15}/></button><button onClick={()=>setZoom(100)}><RotateCcw size={14}/>Actual</button><button onClick={fit}><Maximize2 size={14}/>Fit</button></div></div>
    <div ref={viewport} className={`card-canvas-viewport ${space?'pan-ready':''}`} onPointerDown={e=>{if(!space&&e.button!==1)return;const v=viewport.current;if(!v)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);pan.current={x:e.clientX,y:e.clientY,left:v.scrollLeft,top:v.scrollTop};}} onPointerMove={e=>{const v=viewport.current,p=pan.current;if(!v||!p)return;v.scrollLeft=p.left-(e.clientX-p.x);v.scrollTop=p.top-(e.clientY-p.y);}} onPointerUp={()=>pan.current=null} onPointerCancel={()=>pan.current=null}><div className="card-canvas-stage"><CardArtboardCanvas artboard={active} assets={template.sharedAssets} zoom={zoom} selection={selection} setSelection={setSelection} mutate={mutateTransient} commitMutate={mutate} beginHistoryTransaction={beginHistoryTransaction} endHistoryTransaction={endHistoryTransaction}/></div></div>
    <footer className="card-canvas-status"><span>{status}</span><span>{selection.elementIds.length?`${selection.elementIds.length} selected · Delete removes · Arrow nudge · Shift+Arrow 5 mm`:'Ctrl+Z/Y undo/redo · Ctrl+C/V copy/paste · Ctrl+D duplicate · Hold Space + drag to pan'}</span></footer>
   </section>
   <aside className="card-properties-panel"><div className="card-panel-heading"><div><strong>{primary?'Element Properties':'Artboard Properties'}</strong><small>{primary?'Content, style & transform':'Physical canvas settings'}</small></div></div>{selected.length>1?<MultiSelectionProperties elements={selected} artboardId={active.id} mutate={mutate} groupSelected={groupSelected} ungroupSelected={ungroupSelected}/>:primary?<ElementProperties element={primary} artboardId={active.id} mutate={mutate}/>:<Properties artboard={active} mutate={mutate}/>}</aside>
  </div>
 </div>;
}

type Op={mode:'MOVE';lastX:number;lastY:number;ids:string[]}|{mode:'RESIZE';element:DesignElement;anchor:'NW'|'N'|'NE'|'E'|'SE'|'S'|'SW'|'W';startX:number;startY:number;keepAspect:boolean}|{mode:'ROTATE';element:DesignElement;startAngle:number;startRotation:number};
function CardArtboardCanvas({artboard,assets,zoom,selection,setSelection,mutate,commitMutate,beginHistoryTransaction,endHistoryTransaction}:{artboard:Artboard;assets:DesignTemplate['sharedAssets'];zoom:number;selection:DesignSelectionState;setSelection:(s:DesignSelectionState)=>void;mutate:(f:(t:DesignTemplate)=>DesignTemplate)=>void;commitMutate:(f:(t:DesignTemplate)=>DesignTemplate)=>void;beginHistoryTransaction:()=>void;endHistoryTransaction:()=>void}){
 const canvas=useRef<HTMLDivElement|null>(null);const interaction=useRef<Op|null>(null);const marquee=useRef<{startX:number;startY:number;add:boolean}|null>(null);const [marqueeRect,setMarqueeRect]=useState<DesignRectMm|null>(null);
 const point=(e:React.PointerEvent)=>{const r=canvas.current!.getBoundingClientRect();return{xMm:(e.clientX-r.left)/r.width*artboard.widthMm,yMm:(e.clientY-r.top)/r.height*artboard.heightMm};};
 const downCanvas=(e:React.PointerEvent<HTMLDivElement>)=>{if(e.target!==e.currentTarget&&!(e.target as HTMLElement).classList.contains('card-artboard-empty-state'))return;if(e.button!==0)return;const p=point(e);e.currentTarget.setPointerCapture(e.pointerId);marquee.current={startX:p.xMm,startY:p.yMm,add:e.shiftKey};setMarqueeRect({xMm:p.xMm,yMm:p.yMm,widthMm:0,heightMm:0});if(!e.shiftKey)setSelection(emptySelection(artboard.id));};
 const moveCanvas=(e:React.PointerEvent<HTMLDivElement>)=>{const p=point(e),op=interaction.current;if(op?.mode==='MOVE'){const dx=p.xMm-op.lastX,dy=p.yMm-op.lastY;interaction.current={...op,lastX:p.xMm,lastY:p.yMm};mutate(t=>moveElements(t,artboard.id,op.ids,{xMm:dx,yMm:dy}));return;}if(op?.mode==='RESIZE'){const dx=p.xMm-op.startX,dy=p.yMm-op.startY,base=op.element.size;let w=base.widthMm,h=base.heightMm;if(op.anchor.includes('E'))w+=dx;if(op.anchor.includes('W'))w-=dx;if(op.anchor.includes('S'))h+=dy;if(op.anchor.includes('N'))h-=dy;mutate(t=>resizeElement(t,artboard.id,op.element.id,{widthMm:w,heightMm:h},{anchor:op.anchor,maintainAspectRatio:op.keepAspect}));return;}if(op?.mode==='ROTATE'){const c={xMm:op.element.position.xMm+op.element.size.widthMm/2,yMm:op.element.position.yMm+op.element.size.heightMm/2},angle=Math.atan2(p.yMm-c.yMm,p.xMm-c.xMm);mutate(t=>rotateElement(t,artboard.id,op.element.id,op.startRotation+(angle-op.startAngle)*180/Math.PI));return;}if(marquee.current){const m=marquee.current;setMarqueeRect({xMm:Math.min(m.startX,p.xMm),yMm:Math.min(m.startY,p.yMm),widthMm:Math.abs(p.xMm-m.startX),heightMm:Math.abs(p.yMm-m.startY)});}};
 const upCanvas=()=>{if(marquee.current&&marqueeRect)setSelection(selectByMarquee(artboard,marqueeRect,marquee.current.add?'ADD':'REPLACE',selection));if(interaction.current)endHistoryTransaction();interaction.current=null;marquee.current=null;setMarqueeRect(null);};
 const capture=(ev:React.PointerEvent)=>{ev.stopPropagation();(ev.currentTarget.closest('.card-artboard-canvas') as HTMLElement)?.setPointerCapture?.(ev.pointerId);};
 return <div ref={canvas} className="card-artboard-canvas" data-artboard-id={artboard.id} style={{width:`${artboard.widthMm*MM_TO_CSS_PX}px`,height:`${artboard.heightMm*MM_TO_CSS_PX}px`,transform:`scale(${zoom/100})`,background:bg(artboard)}} onPointerDown={downCanvas} onPointerMove={moveCanvas} onPointerUp={upCanvas} onPointerCancel={upCanvas}>
  {artboard.elements.length===0&&<div className="card-artboard-empty-state"><strong>{artboard.name}</strong><span>Add text, shapes or images from the left panel</span><small>Every element uses the shared Selection & Transform Engine.</small></div>}
  {artboard.elements.filter(e=>e.visible).map(e=>{const isSelected=selection.elementIds.includes(e.id);return <div key={e.id} className={`card-design-element-shell has-visual type-${e.type.toLowerCase()} ${isSelected?'selected':''} ${e.locked?'locked':''}`} style={{left:e.position.xMm*MM_TO_CSS_PX,top:e.position.yMm*MM_TO_CSS_PX,width:e.size.widthMm*MM_TO_CSS_PX,height:e.size.heightMm*MM_TO_CSS_PX,transform:`rotate(${e.rotationDeg}deg)`,opacity:e.opacity,zIndex:e.zIndex}} onPointerDown={ev=>{if(ev.button!==0)return;capture(ev);const p=point(ev);const groupIds=expandElementIdsToGroups(artboard,[e.id]);let next:DesignSelectionState;if(ev.shiftKey){next=selection;for(const gid of groupIds)if(!next.elementIds.includes(gid))next=toggleSelection(next,gid);}else next=isSelected?selection:{artboardId:artboard.id,elementIds:groupIds,primaryElementId:e.id};setSelection(next);if(!e.locked&&next.elementIds.includes(e.id)){beginHistoryTransaction();interaction.current={mode:'MOVE',lastX:p.xMm,lastY:p.yMm,ids:expandElementIdsToGroups(artboard,next.elementIds)};}}}>
    <ElementVisual element={e} assets={assets} mutate={commitMutate} artboardId={artboard.id}/>
    {isSelected&&!e.locked&&<><i className="card-rotation-stem"/><i className="card-rotation-handle" onPointerDown={ev=>{capture(ev);const p=point(ev),c={xMm:e.position.xMm+e.size.widthMm/2,yMm:e.position.yMm+e.size.heightMm/2};beginHistoryTransaction();interaction.current={mode:'ROTATE',element:e,startAngle:Math.atan2(p.yMm-c.yMm,p.xMm-c.xMm),startRotation:e.rotationDeg};}}/>{(['nw','n','ne','e','se','s','sw','w'] as const).map(h=><i key={h} className={`card-transform-handle ${h}`} onPointerDown={ev=>{capture(ev);const p=point(ev);beginHistoryTransaction();interaction.current={mode:'RESIZE',element:e,anchor:h.toUpperCase() as Op extends {mode:'RESIZE';anchor:infer A}?A:never,startX:p.xMm,startY:p.yMm,keepAspect:ev.shiftKey||(e.type==='IMAGE'&&e.maintainAspectRatio===true)};}}/>)}</>}
   </div>})}
  {marqueeRect&&<div className="card-selection-marquee" style={{left:marqueeRect.xMm*MM_TO_CSS_PX,top:marqueeRect.yMm*MM_TO_CSS_PX,width:marqueeRect.widthMm*MM_TO_CSS_PX,height:marqueeRect.heightMm*MM_TO_CSS_PX}}/>}
 </div>;
}

function LayerPanel({artboard,selection,setSelection,mutate,duplicateSelected,groupSelected,ungroupSelected}:{artboard:Artboard;selection:DesignSelectionState;setSelection:(s:DesignSelectionState)=>void;mutate:(f:(t:DesignTemplate)=>DesignTemplate)=>void;duplicateSelected:()=>void;groupSelected:()=>void;ungroupSelected:()=>void}){
 const layers=orderedLayers(artboard);const selectedSet=new Set(selection.elementIds);const selectedGroups=[...new Set(selection.elementIds.map(id=>groupForElement(artboard,id)?.id).filter(Boolean) as string[])];
 return <div className="card-layers-panel"><div className="card-panel-heading"><div><strong>Layers</strong><small>{layers.length} element{layers.length===1?'':'s'}</small></div></div><div className="card-layer-actions"><button onClick={duplicateSelected} disabled={!selection.elementIds.length}>Duplicate</button><button onClick={groupSelected} disabled={selection.elementIds.length<2||selectedGroups.length>0}>Group</button><button onClick={ungroupSelected} disabled={!selectedGroups.length}>Ungroup</button></div><div className="card-layer-list">{layers.length?layers.map(layer=>{const group=groupForElement(artboard,layer.id);return <div key={layer.id} className={`card-layer-row ${selectedSet.has(layer.id)?'active':''}`}><button className="card-layer-main" onClick={()=>setSelection({artboardId:artboard.id,elementIds:expandElementIdsToGroups(artboard,[layer.id]),primaryElementId:layer.id})}><span>{layer.type}</span><input aria-label={`Rename ${layer.name}`} value={layer.name} onClick={e=>e.stopPropagation()} onChange={e=>mutate(t=>renameElement(t,artboard.id,layer.id,e.target.value))}/>{group&&<small>{group.name}</small>}</button><div className="card-layer-mini"><button title={layer.visible?'Hide':'Show'} onClick={()=>mutate(t=>group?setGroupVisibility(t,artboard.id,group.id,!layer.visible):setElementVisibility(t,artboard.id,layer.id,!layer.visible))}>{layer.visible?'◉':'○'}</button><button title={layer.locked?'Unlock':'Lock'} onClick={()=>mutate(t=>group?setGroupLocked(t,artboard.id,group.id,!layer.locked):setElementLocked(t,artboard.id,layer.id,!layer.locked))}>{layer.locked?'🔒':'🔓'}</button><button title="Bring forward" onClick={()=>mutate(t=>moveLayer(t,artboard.id,layer.id,'FORWARD'))}>↑</button><button title="Send backward" onClick={()=>mutate(t=>moveLayer(t,artboard.id,layer.id,'BACKWARD'))}>↓</button><button title="Bring to front" onClick={()=>mutate(t=>moveLayer(t,artboard.id,layer.id,'FRONT'))}>⇈</button><button title="Send to back" onClick={()=>mutate(t=>moveLayer(t,artboard.id,layer.id,'BACK'))}>⇊</button></div></div>}):<div className="card-layer-empty">Add an element to create the first layer.</div>}</div></div>;
}

function ElementVisual({element,assets,mutate,artboardId}:{element:DesignElement;assets:DesignTemplate['sharedAssets'];mutate:(f:(t:DesignTemplate)=>DesignTemplate)=>void;artboardId:string}){
 if(element.type==='TEXT')return <div className="card-text-visual" style={{fontFamily:element.style.fontFamily,fontSize:`${element.style.fontSizePt}pt`,fontWeight:element.style.fontWeight,fontStyle:element.style.italic?'italic':'normal',textDecoration:element.style.underline?'underline':'none',color:element.style.color,textAlign:element.style.alignment.toLowerCase() as 'left'|'center'|'right',lineHeight:element.style.lineHeight,letterSpacing:`${element.style.letterSpacingPt}pt`}} onDoubleClick={ev=>{ev.stopPropagation();const value=window.prompt('Edit text',element.text);if(value!==null)mutate(t=>updateDesignElement(t,artboardId,element.id,e=>e.type==='TEXT'?{...e,text:value}:e));}}>{element.text}</div>;
 if(element.type==='SHAPE')return <ShapeVisual element={element}/>;
 if(element.type==='IMAGE'){const asset=assets.find(a=>a.id===element.assetId);return <div className="card-image-visual" style={{borderRadius:`${element.cornerRadiusMm??0}mm`,border:element.stroke&&element.stroke.style!=='NONE'?`${Math.max(1,element.stroke.widthMm*MM_TO_CSS_PX)}px ${strokeStyle(element.stroke.style)} ${element.stroke.color}`:'none'}}>{asset?<img src={asset.source} alt={element.name} draggable={false} style={{objectFit:element.fit==='FIT'?'contain':element.fit==='FILL'?'cover':'fill',transform:`scale(${element.flipX?-1:1},${element.flipY?-1:1})`}}/>:<div className="card-missing-asset">Missing image</div>}</div>;}
 return <div className="card-unsupported-element">{element.type}</div>;
}

function ShapeVisual({element}:{element:ShapeDesignElement}){const fill=element.fill.type==='SOLID'?element.fill.color:'transparent',fillOpacity=element.fill.type==='SOLID'?(element.fill.opacity??1):1,stroke=element.stroke.style==='NONE'?'none':element.stroke.color,sw=Math.max(.4,element.stroke.widthMm*MM_TO_CSS_PX),dash=element.stroke.style==='DASHED'?'6 4':element.stroke.style==='DOTTED'?'2 3':undefined;const common={fill,fillOpacity,stroke,strokeWidth:sw,strokeDasharray:dash,vectorEffect:'non-scaling-stroke' as const};return <svg className="card-shape-visual" viewBox="0 0 100 100" preserveAspectRatio="none">{shapeNode(element,common)}</svg>;}
function shapeNode(element:ShapeDesignElement,common:Record<string,unknown>){switch(element.shape){case'RECTANGLE':return <rect x="1" y="1" width="98" height="98" {...common}/>;case'ROUNDED_RECTANGLE':return <rect x="1" y="1" width="98" height="98" rx={Math.min(48,(element.cornerRadiusMm??3)*4)} ry={Math.min(48,(element.cornerRadiusMm??3)*4)} {...common}/>;case'CIRCLE':case'ELLIPSE':return <ellipse cx="50" cy="50" rx="48" ry="48" {...common}/>;case'LINE':return <line x1="2" y1="50" x2="98" y2="50" {...common} fill="none"/>;case'TRIANGLE':return <polygon points="50,2 98,98 2,98" {...common}/>;case'ARROW':return <polygon points="2,35 62,35 62,15 98,50 62,85 62,65 2,65" {...common}/>;case'STAR':return <polygon points="50,2 61,36 97,36 68,57 79,92 50,71 21,92 32,57 3,36 39,36" {...common}/>;case'POLYGON':return <polygon points="25,3 75,3 98,50 75,97 25,97 2,50" {...common}/>;case'RIBBON':return <polygon points="2,20 20,20 20,8 80,8 80,20 98,20 88,50 98,80 80,80 80,92 20,92 20,80 2,80 12,50" {...common}/>;case'BADGE':return <polygon points="50,2 62,14 79,9 86,25 97,37 88,52 92,69 76,77 67,94 50,87 33,94 24,77 8,69 12,52 3,37 14,25 21,9 38,14" {...common}/>;default:return null;}}

function ElementProperties({element,artboardId,mutate}:{element:DesignElement;artboardId:string;mutate:(f:(t:DesignTemplate)=>DesignTemplate)=>void}){
 const num=(label:string,value:number,onChange:(v:number)=>void,step='0.1')=><label>{label}<input type="number" step={step} value={normalizeDisplayValue(value)} disabled={element.locked} onChange={e=>{const v=Number(e.target.value);if(Number.isFinite(v))onChange(v);}}/></label>;
 const update=(fn:(e:DesignElement)=>DesignElement)=>mutate(t=>updateDesignElement(t,artboardId,element.id,fn));
 return <div className="card-property-sections"><div className="card-property-note"><strong>{element.name}</strong><span>{element.type}{element.locked?' · Locked':''}</span></div>
  {element.type==='TEXT'&&<TextProperties element={element} update={update}/>} {element.type==='SHAPE'&&<ShapeProperties element={element} update={update}/>} {element.type==='IMAGE'&&<ImageProperties element={element} update={update}/>} 
  <details className="card-property-details" open><summary>Transform</summary><div className="card-property-grid">{num('X (mm)',element.position.xMm,v=>mutate(t=>setElementPosition(t,artboardId,element.id,{xMm:v,yMm:element.position.yMm})))}{num('Y (mm)',element.position.yMm,v=>mutate(t=>setElementPosition(t,artboardId,element.id,{xMm:element.position.xMm,yMm:v})))}{num('Width (mm)',element.size.widthMm,v=>mutate(t=>resizeElement(t,artboardId,element.id,{widthMm:v,heightMm:element.size.heightMm})))}{num('Height (mm)',element.size.heightMm,v=>mutate(t=>resizeElement(t,artboardId,element.id,{widthMm:element.size.widthMm,heightMm:v})))}</div>{num('Rotation (°)',element.rotationDeg,v=>mutate(t=>rotateElement(t,artboardId,element.id,v)))}{num('Opacity',element.opacity,v=>update(e=>({...e,opacity:clamp(v,0,1)})),'0.05')}</details>
  <button className="card-delete-element" disabled={element.locked} onClick={()=>mutate(t=>deleteDesignElements(t,artboardId,[element.id]))}><Trash2 size={14}/>Delete Element</button>
 </div>;
}
function TextProperties({element,update}:{element:TextDesignElement;update:(f:(e:DesignElement)=>DesignElement)=>void}){const patch=(p:Partial<TextDesignElement>)=>update(e=>e.type==='TEXT'?{...e,...p}:e),style=(p:Partial<TextDesignElement['style']>)=>update(e=>e.type==='TEXT'?{...e,style:{...e.style,...p}}:e);return <details className="card-property-details" open><summary>Text</summary><label>Content<textarea value={element.text} onChange={e=>patch({text:e.target.value})}/></label><label>Font<select value={element.style.fontFamily} onChange={e=>style({fontFamily:e.target.value})}>{['Arial','Helvetica','Georgia','Times New Roman','Verdana','Trebuchet MS','Courier New'].map(f=><option key={f}>{f}</option>)}</select></label><div className="card-property-grid"><label>Size (pt)<input type="number" min="1" step="1" value={element.style.fontSizePt} onChange={e=>style({fontSizePt:Math.max(1,Number(e.target.value)||1)})}/></label><label>Weight<select value={element.style.fontWeight} onChange={e=>style({fontWeight:Number(e.target.value)})}><option value="300">Light</option><option value="400">Regular</option><option value="500">Medium</option><option value="600">Semi Bold</option><option value="700">Bold</option><option value="800">Extra Bold</option></select></label></div><div className="card-segmented-control triple"><button className={element.style.italic?'active':''} onClick={()=>style({italic:!element.style.italic})}>Italic</button><button className={element.style.underline?'active':''} onClick={()=>style({underline:!element.style.underline})}>Underline</button><button className={element.style.fontWeight>=700?'active':''} onClick={()=>style({fontWeight:element.style.fontWeight>=700?400:700})}>Bold</button></div><label>Alignment<select value={element.style.alignment} onChange={e=>style({alignment:e.target.value as TextDesignElement['style']['alignment']})}><option value="LEFT">Left</option><option value="CENTER">Center</option><option value="RIGHT">Right</option></select></label><div className="card-property-grid"><label>Line height<input type="number" min="0.5" step="0.1" value={element.style.lineHeight} onChange={e=>style({lineHeight:Math.max(.5,Number(e.target.value)||1.2)})}/></label><label>Letter spacing<input type="number" step="0.1" value={element.style.letterSpacingPt} onChange={e=>style({letterSpacingPt:Number(e.target.value)||0})}/></label></div><label>Text color<div className="card-color-row"><input type="color" value={element.style.color} onChange={e=>style({color:e.target.value})}/><input value={element.style.color} onChange={e=>style({color:e.target.value})}/></div></label></details>;}
function ShapeProperties({element,update}:{element:ShapeDesignElement;update:(f:(e:DesignElement)=>DesignElement)=>void}){const patch=(p:Partial<ShapeDesignElement>)=>update(e=>e.type==='SHAPE'?{...e,...p}:e);const fillColor=element.fill.type==='SOLID'?element.fill.color:'#dbeafe';const fillMode=element.fill.type==='NONE'?'TRANSPARENT':'SOLID';return <details className="card-property-details" open><summary>Shape</summary><label>Shape<select value={element.shape} onChange={e=>patch({shape:e.target.value as DesignShapeKind})}>{SHAPES.map(s=><option key={s} value={s}>{shapeLabel(s)}</option>)}</select></label><div className="card-property-grid"><label>Fill<select value={fillMode} onChange={e=>patch({fill:e.target.value==='TRANSPARENT'?{type:'NONE'}:{type:'SOLID',color:fillColor,opacity:1}})}><option value="SOLID">Solid</option><option value="TRANSPARENT">Transparent</option></select></label><label>Border<select value={element.stroke.style} onChange={e=>patch({stroke:{...element.stroke,style:e.target.value as ShapeDesignElement['stroke']['style']}})}><option value="SOLID">Solid</option><option value="DASHED">Dashed</option><option value="DOTTED">Dotted</option><option value="NONE">None</option></select></label></div>{fillMode==='SOLID'&&<label>Fill color<div className="card-color-row"><input type="color" value={fillColor} onChange={e=>patch({fill:{type:'SOLID',color:e.target.value,opacity:1}})}/><input value={fillColor} readOnly/></div></label>}{element.stroke.style!=='NONE'&&<><label>Border color<div className="card-color-row"><input type="color" value={element.stroke.color} onChange={e=>patch({stroke:{...element.stroke,color:e.target.value}})}/><input value={element.stroke.color} readOnly/></div></label><label>Border width (mm)<input type="number" min="0" step="0.1" value={element.stroke.widthMm} onChange={e=>patch({stroke:{...element.stroke,widthMm:Math.max(0,Number(e.target.value)||0)}})}/></label></>}{(element.shape==='ROUNDED_RECTANGLE'||element.shape==='RECTANGLE')&&<label>Corner radius (mm)<input type="number" min="0" step="0.5" value={element.cornerRadiusMm??0} onChange={e=>patch({cornerRadiusMm:Math.max(0,Number(e.target.value)||0)})}/></label>}</details>;}
function ImageProperties({element,update}:{element:ImageDesignElement;update:(f:(e:DesignElement)=>DesignElement)=>void}){const patch=(p:Partial<ImageDesignElement>)=>update(e=>e.type==='IMAGE'?{...e,...p}:e);return <details className="card-property-details" open><summary>Image</summary><label>Fit<select value={element.fit} onChange={e=>patch({fit:e.target.value as ImageDesignElement['fit']})}><option value="FIT">Fit</option><option value="FILL">Fill</option><option value="STRETCH">Stretch</option></select></label><div className="card-segmented-control"><button className={element.flipX?'active':''} onClick={()=>patch({flipX:!element.flipX})}>Flip X</button><button className={element.flipY?'active':''} onClick={()=>patch({flipY:!element.flipY})}>Flip Y</button></div><label className="card-check-row"><input type="checkbox" checked={element.maintainAspectRatio??true} onChange={e=>patch({maintainAspectRatio:e.target.checked})}/>Lock aspect ratio</label><label>Corner radius (mm)<input type="number" min="0" step="0.5" value={element.cornerRadiusMm??0} onChange={e=>patch({cornerRadiusMm:Math.max(0,Number(e.target.value)||0)})}/></label></details>;}
function MultiSelectionProperties({elements,artboardId,mutate,groupSelected,ungroupSelected}:{elements:DesignElement[];artboardId:string;mutate:(f:(t:DesignTemplate)=>DesignTemplate)=>void;groupSelected:()=>void;ungroupSelected:()=>void}){const b=getSelectionBounds(elements),ids=elements.map(e=>e.id),grouped=elements.some(e=>e.groupId);return <div className="card-property-sections"><div className="card-property-note"><strong>{elements.length} elements selected</strong><span>Move together. Phase 6.0.5 also supports flat grouping, shared scaling and rotation.</span></div><div className="card-layer-action-grid"><button onClick={groupSelected} disabled={grouped}>Group</button><button onClick={ungroupSelected} disabled={!grouped}>Ungroup</button><button onClick={()=>mutate(t=>scaleElements(t,artboardId,ids,1.1))}>Scale +10%</button><button onClick={()=>mutate(t=>rotateElementsAsGroup(t,artboardId,ids,15))}>Rotate +15°</button></div>{b&&<div className="card-property-grid"><label>X (mm)<input readOnly value={normalizeDisplayValue(b.xMm)}/></label><label>Y (mm)<input readOnly value={normalizeDisplayValue(b.yMm)}/></label><label>Width (mm)<input readOnly value={normalizeDisplayValue(b.widthMm)}/></label><label>Height (mm)<input readOnly value={normalizeDisplayValue(b.heightMm)}/></label></div>}</div>}
function Properties({artboard,mutate}:{artboard:Artboard;mutate:(f:(t:DesignTemplate)=>DesignTemplate)=>void}){const unit=artboard.displayUnit,w=normalizeDisplayValue(mmToUnit(artboard.widthMm,unit)),h=normalizeDisplayValue(mmToUnit(artboard.heightMm,unit)),preset=ARTBOARD_PRESETS.find(p=>near(p.widthMm,artboard.widthMm)&&near(p.heightMm,artboard.heightMm));const dimensions=(nw:number,nh:number)=>{const wm=unitToMm(nw,unit),hm=unitToMm(nh,unit);if(wm>0&&hm>0&&Number.isFinite(wm)&&Number.isFinite(hm))mutate(t=>resizeArtboard(t,artboard.id,wm,hm));};return <div className="card-property-sections"><label>Name<input value={artboard.name} onChange={e=>{if(e.target.value.trim())mutate(t=>renameArtboard(t,artboard.id,e.target.value));}}/></label><label>Preset<select value={preset?.id??'custom'} onChange={e=>{const p=ARTBOARD_PRESETS.find(x=>x.id===e.target.value);if(p)mutate(t=>resizeArtboard(t,artboard.id,p.widthMm,p.heightMm));}}><option value="custom">Custom</option>{ARTBOARD_PRESETS.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><div className="card-property-grid"><label>Width ({unit==='MM'?'mm':'in'})<input type="number" min="0.001" step="0.1" value={w} onChange={e=>dimensions(Number(e.target.value),h)}/></label><label>Height ({unit==='MM'?'mm':'in'})<input type="number" min="0.001" step="0.1" value={h} onChange={e=>dimensions(w,Number(e.target.value))}/></label></div><label>Display unit<select value={unit} onChange={e=>mutate(t=>setArtboardDisplayUnit(t,artboard.id,e.target.value as DesignUnit))}><option value="MM">Millimetres (mm)</option><option value="IN">Inches (in)</option></select></label><label>Orientation<div className="card-segmented-control"><button className={artboard.widthMm>=artboard.heightMm?'active':''} onClick={()=>{if(artboard.widthMm<artboard.heightMm)mutate(t=>resizeArtboard(t,artboard.id,artboard.heightMm,artboard.widthMm));}}>Landscape</button><button className={artboard.heightMm>artboard.widthMm?'active':''} onClick={()=>{if(artboard.heightMm<=artboard.widthMm)mutate(t=>resizeArtboard(t,artboard.id,artboard.heightMm,artboard.widthMm));}}>Portrait</button></div></label><label>Background<div className="card-color-row"><input type="color" value={color(artboard)} onChange={e=>mutate(t=>setArtboardBackground(t,artboard.id,{type:'SOLID',color:e.target.value,opacity:1}))}/><input value={color(artboard)} readOnly/></div></label><div className="card-property-note"><strong>Phase 6.0.5</strong><span>Layers, deterministic z-order and flat grouping now build on the shared element/transform foundation.</span></div></div>}

const color=(a:Artboard)=>a.background.type==='SOLID'?a.background.color:'#ffffff';const bg=(a:Artboard)=>a.background.type==='SOLID'?a.background.color:'#ffffff';const near=(a:number,b:number)=>Math.abs(a-b)<.001;const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,v));const sizeText=(a:Artboard)=>a.displayUnit==='IN'?`${normalizeDisplayValue(mmToUnit(a.widthMm,'IN'))} × ${normalizeDisplayValue(mmToUnit(a.heightMm,'IN'))} in`:`${normalizeDisplayValue(a.widthMm)} × ${normalizeDisplayValue(a.heightMm)} mm`;const isForm=(t:EventTarget|null)=>t instanceof HTMLInputElement||t instanceof HTMLTextAreaElement||t instanceof HTMLSelectElement||t instanceof HTMLButtonElement;const shapeLabel=(s:DesignShapeKind)=>s.toLowerCase().split('_').map(p=>p.charAt(0).toUpperCase()+p.slice(1)).join(' ');const strokeStyle=(s:'SOLID'|'DASHED'|'DOTTED'|'NONE')=>s==='DASHED'?'dashed':s==='DOTTED'?'dotted':'solid';
function readAsDataUrl(file:File):Promise<string>{return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>typeof r.result==='string'?resolve(r.result):reject(new Error('Unable to read image.'));r.onerror=()=>reject(r.error??new Error('Unable to read image.'));r.readAsDataURL(file);});}
function readImageDimensions(src:string):Promise<{widthPx:number;heightPx:number}>{return new Promise(resolve=>{const image=new Image();image.onload=()=>resolve({widthPx:image.naturalWidth,heightPx:image.naturalHeight});image.onerror=()=>resolve({widthPx:0,heightPx:0});image.src=src;});}
