import type { Artboard, DesignFill, DesignInsets, DesignTemplate, DesignUnit } from '@document-tool/contracts';
export interface ArtboardPreset { id:string; label:string; widthMm:number; heightMm:number; category:'CARD'|'LABEL'|'PAPER'|'CUSTOM'; }
export const ARTBOARD_PRESETS:readonly ArtboardPreset[]=[
{id:'business-card-90x50',label:'Business Card · 90 × 50 mm',widthMm:90,heightMm:50,category:'CARD'},
{id:'business-card-85x55',label:'Business Card · 85 × 55 mm',widthMm:85,heightMm:55,category:'CARD'},
{id:'id-card-cr80',label:'ID Card · 85.60 × 53.98 mm',widthMm:85.6,heightMm:53.98,category:'CARD'},
{id:'a6',label:'A6 · 105 × 148 mm',widthMm:105,heightMm:148,category:'PAPER'},
{id:'a5',label:'A5 · 148 × 210 mm',widthMm:148,heightMm:210,category:'PAPER'},
{id:'a4',label:'A4 · 210 × 297 mm',widthMm:210,heightMm:297,category:'PAPER'}];
export const EMPTY_INSETS:DesignInsets=Object.freeze({topMm:0,rightMm:0,bottomMm:0,leftMm:0});
const EMPTY_FILL:DesignFill=Object.freeze({type:'SOLID',color:'#ffffff',opacity:1});
export const mmToUnit=(valueMm:number,unit:DesignUnit)=>unit==='IN'?valueMm/25.4:valueMm;
export const unitToMm=(value:number,unit:DesignUnit)=>unit==='IN'?value*25.4:value;
export const normalizeDisplayValue=(value:number)=>Number(value.toFixed(3));
export function createBlankArtboard(input:{id:string;name:string;order:number;widthMm:number;heightMm:number;displayUnit?:DesignUnit;background?:DesignFill}):Artboard{return{id:input.id,name:input.name.trim()||`Artboard ${input.order+1}`,order:input.order,widthMm:input.widthMm,heightMm:input.heightMm,displayUnit:input.displayUnit??'MM',background:input.background??{...EMPTY_FILL},print:{bleed:{...EMPTY_INSETS},safeArea:{...EMPTY_INSETS}},guides:[],groups:[],elements:[]};}
export function normalizeArtboardOrder(artboards:readonly Artboard[]):Artboard[]{return[...artboards].sort((a,b)=>a.order-b.order).map((a,i)=>({...a,order:i}));}
export function addArtboard(template:DesignTemplate,artboard:Artboard):DesignTemplate{return{...template,artboards:normalizeArtboardOrder([...template.artboards,artboard])};}
export function duplicateArtboard(template:DesignTemplate,sourceId:string,newId:string,newName?:string):DesignTemplate{const ordered=normalizeArtboardOrder(template.artboards);const index=ordered.findIndex(a=>a.id===sourceId);if(index<0)throw new Error(`Artboard not found: ${sourceId}`);const clone=structuredClone(ordered[index]!);clone.id=newId;clone.name=newName?.trim()||`${clone.name} Copy`;clone.order=index+1;clone.guides=clone.guides.map((g,i)=>({...g,id:`${newId}-guide-${i+1}`}));const groupIdMap=new Map(clone.groups.map((g,i)=>[g.id,`${newId}-group-${i+1}`]));const elementIdMap=new Map(clone.elements.map((e,i)=>[e.id,`${newId}-element-${i+1}`]));clone.groups=clone.groups.map(g=>({...g,id:groupIdMap.get(g.id)!,parentGroupId:g.parentGroupId?groupIdMap.get(g.parentGroupId):undefined,elementIds:g.elementIds.map(elementId=>elementIdMap.get(elementId)??elementId)}));clone.elements=clone.elements.map(e=>({...e,id:elementIdMap.get(e.id)!,groupId:e.groupId?groupIdMap.get(e.groupId):undefined}));return{...template,artboards:normalizeArtboardOrder([...ordered.slice(0,index+1),clone,...ordered.slice(index+1)])};}
export function renameArtboard(template:DesignTemplate,id:string,name:string):DesignTemplate{const n=name.trim();if(!n)throw new Error('Artboard name is required.');return{...template,artboards:template.artboards.map(a=>a.id===id?{...a,name:n}:a)};}
export function deleteArtboard(template:DesignTemplate,id:string):DesignTemplate{if(template.artboards.length<=1)throw new Error('A design template must keep at least one artboard.');const next=template.artboards.filter(a=>a.id!==id);if(next.length===template.artboards.length)throw new Error(`Artboard not found: ${id}`);return{...template,artboards:normalizeArtboardOrder(next)};}
export function moveArtboard(template:DesignTemplate,id:string,direction:-1|1):DesignTemplate{const ordered=normalizeArtboardOrder(template.artboards);const index=ordered.findIndex(a=>a.id===id);if(index<0)throw new Error(`Artboard not found: ${id}`);const target=index+direction;if(target<0||target>=ordered.length)return{...template,artboards:ordered};const next=[...ordered];[next[index],next[target]]=[next[target]!,next[index]!];return{...template,artboards:next.map((artboard,order)=>({...artboard,order}))};}
export function resizeArtboard(template:DesignTemplate,id:string,widthMm:number,heightMm:number):DesignTemplate{if(!Number.isFinite(widthMm)||!Number.isFinite(heightMm)||widthMm<=0||heightMm<=0)throw new Error('Artboard width and height must be positive numbers.');return{...template,artboards:template.artboards.map(a=>a.id===id?{...a,widthMm,heightMm}:a)};}
export function setArtboardDisplayUnit(template:DesignTemplate,id:string,displayUnit:DesignUnit):DesignTemplate{return{...template,artboards:template.artboards.map(a=>a.id===id?{...a,displayUnit}:a)};}
export function setArtboardBackground(template:DesignTemplate,id:string,background:DesignFill):DesignTemplate{return{...template,artboards:template.artboards.map(a=>a.id===id?{...a,background}:a)};}
