import type {DesignElement,PathDesignElement,PathGeometry,PathPoint,PathSegment} from '@document-tool/contracts';
import {getPathEndpoints,localToWorld,worldToLocal} from './pathUtils.js';

const INTERSECTION_EPS=1e-6;
export const INTERSECTION_CLUSTER_TOLERANCE_MM=.2;
type Point={x:number;y:number};
type Request={segmentId:string;t:number;world:Point};
type Endpoint={element:PathDesignElement;pointId:string;segmentId:string;t:0|1;world:Point;declared:boolean};

function crossing(a:Point,b:Point,c:Point,d:Point):{point:Point;t:number;u:number}|undefined{const rx=b.x-a.x,ry=b.y-a.y,sx=d.x-c.x,sy=d.y-c.y,den=rx*sy-ry*sx;if(Math.abs(den)<1e-9)return undefined;const qx=c.x-a.x,qy=c.y-a.y,t=(qx*sy-qy*sx)/den,u=(qx*ry-qy*rx)/den;if(t<-INTERSECTION_EPS||t>1+INTERSECTION_EPS||u<-INTERSECTION_EPS||u>1+INTERSECTION_EPS)return undefined;const tc=Math.max(0,Math.min(1,t)),uc=Math.max(0,Math.min(1,u));return{point:{x:a.x+rx*tc,y:a.y+ry*tc},t:tc,u:uc};}
function projection(point:Point,a:Point,b:Point):{point:Point;t:number;distance:number}{const dx=b.x-a.x,dy=b.y-a.y,len2=dx*dx+dy*dy,t=len2<1e-12?0:Math.max(0,Math.min(1,((point.x-a.x)*dx+(point.y-a.y)*dy)/len2)),projected={x:a.x+dx*t,y:a.y+dy*t};return{point:projected,t,distance:Math.hypot(point.x-projected.x,point.y-projected.y)};}
function lineSegments(element:PathDesignElement){const byId=new Map(element.geometry.points.map(point=>[point.id,point] as const));return element.geometry.segments.flatMap(segment=>{if(segment.type!=='LINE')return[];const from=byId.get(segment.fromPointId),to=byId.get(segment.toPointId);return from&&to?[{segment,from:localToWorld(from,element),to:localToWorld(to,element)}]:[];});}
function addRequest(requests:Map<string,Request[]>,elementId:string,request:Request){const list=requests.get(elementId)??[];if(!list.some(existing=>existing.segmentId===request.segmentId&&Math.abs(existing.t-request.t)<INTERSECTION_EPS&&Math.hypot(existing.world.x-request.world.x,existing.world.y-request.world.y)<INTERSECTION_CLUSTER_TOLERANCE_MM))list.push(request);requests.set(elementId,list);}

/** Inserts and consolidates persistent nodes for focused straight PATH topology. */
export function materializeStraightPathIntersections(elements:readonly DesignElement[],focusIds:readonly string[]):DesignElement[]{
 const focus=new Set(focusIds),paths=elements.filter((element):element is PathDesignElement=>element.type==='PATH'&&element.visible&&!element.locked&&!element.runtimeHidden&&!['XLINE','RAY'].includes(String(element.metadata?.cadGeometryKind))),requests=new Map<string,Request[]>();
 const endpoints:Endpoint[]=paths.flatMap(element=>{const ids=new Set(getPathEndpoints(element.geometry)),declared=new Set(Array.isArray(element.metadata?.intersectionNodeIds)?element.metadata.intersectionNodeIds.filter((value):value is string=>typeof value==='string'):[]);return element.geometry.points.flatMap(point=>{if(!ids.has(point.id))return[];const segment=element.geometry.segments.find(item=>item.fromPointId===point.id||item.toPointId===point.id);if(!segment||segment.type!=='LINE')return[];return[{element,pointId:point.id,segmentId:segment.id,t:segment.fromPointId===point.id?0:1,world:localToWorld(point,element),declared:declared.has(point.id)} as Endpoint];});});
 const visited=new Set<number>();for(let seed=0;seed<endpoints.length;seed++){if(visited.has(seed))continue;const cluster:number[]=[seed],queue=[seed];visited.add(seed);while(queue.length){const current=queue.shift()!;for(let index=0;index<endpoints.length;index++){if(visited.has(index)||Math.hypot(endpoints[current]!.world.x-endpoints[index]!.world.x,endpoints[current]!.world.y-endpoints[index]!.world.y)>INTERSECTION_CLUSTER_TOLERANCE_MM)continue;visited.add(index);queue.push(index);cluster.push(index);}}const members=cluster.map(index=>endpoints[index]!),elementIds=new Set(members.map(member=>member.element.id));if(elementIds.size<2||!members.some(member=>focus.has(member.element.id)))continue;const canonical=[...members].sort((a,b)=>Number(b.declared)-Number(a.declared)||a.element.zIndex-b.element.zIndex||a.element.id.localeCompare(b.element.id)||a.pointId.localeCompare(b.pointId))[0]!.world;for(const member of members)addRequest(requests,member.element.id,{segmentId:member.segmentId,t:member.t,world:canonical});}
 for(let i=0;i<paths.length;i++)for(let j=i+1;j<paths.length;j++){const first=paths[i]!,second=paths[j]!;if(!focus.has(first.id)&&!focus.has(second.id))continue;for(const a of lineSegments(first))for(const b of lineSegments(second)){const hit=crossing(a.from,a.to,b.from,b.to);if(hit){addRequest(requests,first.id,{segmentId:a.segment.id,t:hit.t,world:hit.point});addRequest(requests,second.id,{segmentId:b.segment.id,t:hit.u,world:hit.point});continue;}for(const candidate of [{point:a.from,t:0 as const},{point:a.to,t:1 as const}]){const projected=projection(candidate.point,b.from,b.to);if(projected.distance<=INTERSECTION_CLUSTER_TOLERANCE_MM&&projected.t>INTERSECTION_EPS&&projected.t<1-INTERSECTION_EPS){addRequest(requests,first.id,{segmentId:a.segment.id,t:candidate.t,world:projected.point});addRequest(requests,second.id,{segmentId:b.segment.id,t:projected.t,world:projected.point});}}for(const candidate of [{point:b.from,t:0 as const},{point:b.to,t:1 as const}]){const projected=projection(candidate.point,a.from,a.to);if(projected.distance<=INTERSECTION_CLUSTER_TOLERANCE_MM&&projected.t>INTERSECTION_EPS&&projected.t<1-INTERSECTION_EPS){addRequest(requests,second.id,{segmentId:b.segment.id,t:candidate.t,world:projected.point});addRequest(requests,first.id,{segmentId:a.segment.id,t:projected.t,world:projected.point});}}}}
 return elements.map(element=>{if(element.type!=='PATH')return element;const elementRequests=requests.get(element.id);if(!elementRequests?.length)return element;const originalById=new Map(element.geometry.points.map(point=>[point.id,point] as const)),points:PathPoint[]=element.geometry.points.map(point=>({...point,inHandle:point.inHandle?{...point.inHandle}:undefined,outHandle:point.outHandle?{...point.outHandle}:undefined})),segments:PathSegment[]=[],intersectionIds=new Set(Array.isArray(element.metadata?.intersectionNodeIds)?element.metadata.intersectionNodeIds.filter((value):value is string=>typeof value==='string'):[]);
  const movePoint=(pointId:string,world:Point)=>{const point=points.find(item=>item.id===pointId);if(!point)return;const local=worldToLocal(world,element),dx=local.x-point.x,dy=local.y-point.y;point.x=local.x;point.y=local.y;if(point.inHandle)point.inHandle={x:point.inHandle.x+dx,y:point.inHandle.y+dy};if(point.outHandle)point.outHandle={x:point.outHandle.x+dx,y:point.outHandle.y+dy};intersectionIds.add(pointId);};
  for(const segment of element.geometry.segments){const hits=elementRequests.filter(request=>request.segmentId===segment.id).sort((a,b)=>a.t-b.t).filter((request,index,array)=>index===0||Math.abs(request.t-array[index-1]!.t)>INTERSECTION_EPS);if(segment.type!=='LINE'||!hits.length){segments.push({...segment});continue;}const from=originalById.get(segment.fromPointId),to=originalById.get(segment.toPointId);if(!from||!to){segments.push({...segment});continue;}const chain=[segment.fromPointId];for(const hit of hits){if(hit.t<=INTERSECTION_EPS){movePoint(segment.fromPointId,hit.world);continue;}if(hit.t>=1-INTERSECTION_EPS){movePoint(segment.toPointId,hit.world);continue;}const local=worldToLocal(hit.world,element),existing=points.find(point=>Math.hypot(point.x-local.x,point.y-local.y)<=INTERSECTION_EPS),pointId=existing?.id??crypto.randomUUID();if(!existing)points.push({id:pointId,x:local.x,y:local.y,mode:'CORNER'});intersectionIds.add(pointId);if(chain.at(-1)!==pointId)chain.push(pointId);}if(chain.at(-1)!==segment.toPointId)chain.push(segment.toPointId);for(let index=0;index<chain.length-1;index++)segments.push({id:index===0?segment.id:crypto.randomUUID(),type:'LINE',fromPointId:chain[index]!,toPointId:chain[index+1]!});}
  const geometry:PathGeometry={...element.geometry,points,segments};return{...element,geometry,metadata:{...element.metadata,intersectionNodeIds:[...intersectionIds],intersectionTopologyVersion:2}};
 });
}
